### ISSUE TITLE
1.0.0-ALPHA-x Breaks README, and does not work properly for development

### ISSUE THREAD

**Issue by andybdahl** [rickclephas/KMP-NativeCoroutines#106]
Hi Rick,

We are using you library for our application here at a Danish company, and thank you for your support to the KMP community 💪

I noticed that the README has been plastered with info on the new ALPHA releases, so we cannot read KSP versions and documentation for the stable versions anymore (the 0.13.x versions), which I think is a problem as the new release is still alpha, and not yet ready for use.
Could you update the readme to include information on how to use the stable version again?

I already tested upgrading to the 1.0.0 version and it does not work, it seems the functions and variables with the new @NativeCoroutines annotation are being generated as Static functions now instead of member functions. We are using the @NativeCoroutines annotation on an interface instead of a class though, so I presume it could be because of that.

**Comment by rickclephas** [comment]
Hi, thanks for using KMP-NativeCoroutines!

Yeah since the 0.x releases are no longer maintained (they weren't really stable) I have updated the README for the 1.0 releases. The old README for the 0.x release can be found [here](https://github.com/rickclephas/KMP-NativeCoroutines/blob/f0d9c952ee0b27b30dc4e2b704d91b242a14b20e/README.md).

Note: the 1.0 release is still in alpha because there are some missing features that need to be added before we can really call it stable 😄.

> I already tested upgrading to the 1.0.0 version and it does not work, it seems the functions and variables with the new @NativeCoroutines annotation are being generated as Static functions now instead of member functions. We are using the @NativeCoroutines annotation on an interface instead of a class though, so I presume it could be because of that.

Yeah that is correct. The 1.0 releases use KSP (due to some stability issues with the older approach) which isn't able to modify existing classes, so it generates extension properties and functions.

This has an unfortunate side effect for usage with interfaces since ObjC doesn't support extensions on protocols.
However the extensions should still be accessible to Swift (please let me know if they are not).

In order to make it more usable with interfaces you could manually add extensions to your interface in Swift (something like [this](https://github.com/rickclephas/KMP-NativeCoroutines/issues/103#issuecomment-1501096118)). An added bonus would be that your declarations can directly expose a Combine Publisher (or any of the other Swift implementations).

**Comment by andybdahl** [comment]
Hi Rick,

thanks for the link to the old readme 👍 I assumed the older version was stable because of the naming, but that is fine.
Using KSP for the new versions is a good shift, but I think we will wait a little bit for the update, as extensions are not supported in ObjC. When I say extensions I mean functions that looks like member functions, and although like you say the KSP version does implement static functions that takes an instance of the interface and the extentions arguments, that is not an extension when the iOS devs needs to call it, that is still a static call seen from Swift to the *NativeKt file, so it requires all the function calls from a 0.13.x version to be rewritten in Swift to the new version, so that is a bit unfortunate. I can't think of a way of using KSP that does not break the old schema though, so maybe we'll just have to do the shift soon anyway

**Comment by rickclephas** [comment]
@lotdrops unfortunately that isn't as easy as you would imagine. The main problem is that the ObjC/Swift names of your Kotlin declarations aren't deterministic. Since there is currently no compiler hook to get the actual names you would have to guess the final name. That would be verify error prone.

P.S. in general I would try to avoid interfaces. Sadly the Kotlin-ObjC-Swift interop for interfaces has some major limitations.
