### ISSUE TITLE
@NativeCoroutineState properties change type with nullability

### ISSUE THREAD

**Issue by humblehacker** [rickclephas/KMP-NativeCoroutines#119]
Given the following property in a Kotlin view model class:

```kotlin
@NativeCoroutineState
val price: StateFlow<Double>
```

it is exposed to Swift as:

```swift
let price: Double = viewModel.price
```

But if I make it nullable:

```kotlin
@NativeCoroutineState
val price: StateFlow<Double?>
```

I get this in Swift:

```swift
let price: KotlinDouble? = viewModel.price
```

which requires ugly conversion on the Swift side (especially with bindings).

Is there something I can do to improve this?

**Comment by rickclephas** [comment]
Hi! This is an unfortunate limitation of the Objective-C interop. ObjC doesn't support nullable primitives (only classes are allowed to be `null`) which is why `Double?` becomes `KotlinDouble?`.

A workaround for this would be to refine this declaration in Swift:
```kotlin
@file:OptIn(ExperimentalObjCRefinement::class, ExperimentalObjCName::class)

class MyClass {
    @HiddenFromObjC
    val price: StateFlow<Double?>
}

@ObjCName("price")
@ShouldRefineInSwift
val MyClass.priceValue: Double?
    get() = price.value
```

```swift
extension MyClass {
    var price: Double? {
        self.__price?.doubleValue
    }
}
```

It won't really solve the issue, but it does reduce the required boilerplate.
I'll see if I can find some way to reduce the boilerplate even more 😄.

**Comment by humblehacker** [comment]
Thanks for suggesting the workaround :) I look forward to any improvements you can come up with.

**Comment by rickclephas** [comment]
FYI [v1.0.0-ALPHA-12](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-12) introduces the `NativeCoroutinesRefined` and `NativeCoroutinesRefinedState` annotations that generate the required Kotlin code.
