### ISSUE TITLE
Couple of issues with SPM

### ISSUE THREAD

**Issue by ychescale9** [rickclephas/KMP-NativeCoroutines#14]
Thanks for adding SPM support!

It works great locally but fails on CI as the repo url seems to be only available with `ssh`:

![image](https://user-images.githubusercontent.com/11519072/139606010-8297a6f1-4952-4221-8edb-03509d613420.png)
Is it possible to support `https` as well which I think is what most packages do?

The other thing I noticed is XCode always adds the `RxSwift` transitive dependency even when I've only added the `KMPNativeCoroutinesCombine` library. Not sure if there's anything you can do here as I see in the `Package.swift` you've only added the `RxSwift` dependency to the `KMPNativeCoroutinesRxSwift ` target?

**Comment by rickclephas** [comment]
>  Is it possible to support `https` as well which I think is what most packages do?

Yeah you should be able to use `https://github.com/rickclephas/KMP-NativeCoroutines.git` as the URL as well.

> The other thing I noticed is XCode always adds the `RxSwift` transitive dependency even when I've only added the `KMPNativeCoroutinesCombine` library. Not sure if there's anything you can do here as I see in the `Package.swift` you've only added the `RxSwift` dependency to the `KMPNativeCoroutinesRxSwift ` target?

I am no expert on SPM, but to me it seems there are currently a couple of limitations.
All of which are caused by multiple products in a single `Package.swift` file.
The dependency issue you mention is one of them. 
The other one is the supported platforms which can't be set per product. Meaning `KMPNativeCoroutinesCore` and `KMPNativeCoroutinesRxSwift` now "require" iOS 13 instead of iOS 9.

I am afraid I can't do much about both. Let me know if you know of a way I can 🙂.

**Comment by ychescale9** [comment]
> Yeah you should be able to use https://github.com/rickclephas/KMP-NativeCoroutines.git as the URL as well.

Cool not sure why it didn't work before 😅 

> I am afraid I can't do much about both. Let me know if you know of a way I can

The fork we were using uses `exclude`, and we didn't have that issue. Not sure if this helps?
https://github.com/Lorex7/KMP-NativeCoroutines/commit/dccf87e506f4aa69f7edce57a590fd70e453b31f

**Comment by rickclephas** [comment]
> The fork we were using uses `exclude`, and we didn't have that issue. Not sure if this helps? [Lorex7@dccf87e](https://github.com/Lorex7/KMP-NativeCoroutines/commit/dccf87e506f4aa69f7edce57a590fd70e453b31f)

The excludes shouldn't be necessary as they are relative to the target path (which is already set to the correct subfolder). The reason you weren't seeing the RxSwift dependency is because it isn't defined in the fork.
I think the solution you are looking for is described in [SE-0226](https://github.com/apple/swift-evolution/blob/master/proposals/0226-package-manager-target-based-dep-resolution.md).

**Comment by ychescale9** [comment]
Thanks! Someone suggested [this](https://forums.swift.org/t/do-not-resolve-unneeded-dependencies/33912/7) but that sounds like a lot of maintenance overheads 🥲

**Comment by rickclephas** [comment]
That indeed sounds like a lot of overhead 😅.

Like I said I am no SPM expert so I can't really determine how bad the RxSwift dependency is.
I mean I would assume that if you are not using the RxSwift implementation it won't actually build and include RxSwift in your app, right?

Besides that how would different versions work?
The async implementation is a separate version (with the `-swift-async-await` suffix) for now (due to the Xcode beta requirement).
Can you still use version ranges with such a version? Or does that mean you will be locked to a specific version instead?

I am always open to look into workarounds, but as I see it now there isn't really a "perfect" workaround for this...

**Comment by ychescale9** [comment]
Thanks. I'm also just starting out with SPM and learning some of its quirks.

I'm closing this now as there's not much we can do (that we know of).

**Comment by rickclephas** [comment]
Okay so I though about this some more and added some SPM tags.
You can now add only a specific implementation via the SPM by using the SPM version suffixes.
E.g. for `v0.7.0` you can use the following SPM versions:
- `v0.7.0-spm-async`
- `v0.7.0-spm-combine`
- `v0.7.0-spm-rxswift`

These versions only contain a single implementation/library in the `Package.swift` file.
This "fixes" the above mentioned limitation with the single `Package.swift` file.
Though it does require you to use an exact version instead of e.g. a range.

**NOTE:** this might be a pain to keep maintaining so I might decide to drop these SPM versions later 😅.

**Comment by ychescale9** [comment]
Thanks!

**Comment by ychescale9** [comment]
@rickclephas thanks for still maintaining the `spm-async` releases 😄 . I'm just wondering if there's any way to get the `-new-mm` version of these spm only releases?

**Comment by rickclephas** [comment]
NP! It's all automated 😅.

You can actually just combine these versions.
`v0.12.0-spm-async` is identical to `v0.12.0` (it just doesn't contain the other Swift implementations) and `v0.12.0-new-mm` is also identical to `v0.12.0`, the only difference being the usage of the non `-native-mt` coroutines library (and no more `freeze` calls).

So it's perfectly fine to use `v0.12.0-new-mm` in Kotlin and `v0.12.0-spm-async` in Swift.

**Comment by ychescale9** [comment]
Thanks! I was somehow expecting a `new-mm` version of the Swift package which obviously doesn't make sense 😂

**Comment by phi161** [comment]
In my setup, I've been using the `X.X.X-spm-async` version successfully like this: 
```
dependencies: [
    .package(url: "https://github.com/rickclephas/KMP-NativeCoroutines.git", exact: "0.13.2-spm-async"),
],
```
but now I unfortunately need Combine as well: `...exact: "0.13.2-spm-combine"`.

I guess I have to use `0.13.2` to have both async & combine, right?
If this is the case, would it be possible to _not_ bring in the RxSwift dependency somehow?

**Comment by rickclephas** [comment]
Hi @phi161. I have just pushed another tag `-spm-no-deps` which contains everything expect for the RxSwift implementation. That should do the trick 😄.

**Comment by phi161** [comment]
Works like a charm, thanks a lot for taking the time to fix this!
