### ISSUE TITLE
Add "support" for all Kotlin targets

### ISSUE THREAD

**Issue by drampelt** [rickclephas/KMP-NativeCoroutines#15]
When adding the gradle plugin it to my kotlin multiplatform module and syncing with IDE, all of the source sets except the android ones get removed from the IDE.

I get this message:
![image](https://user-images.githubusercontent.com/401214/140190484-f3e53d11-3336-442d-8aa6-3dbe0dfdb2d5.png)

Also, in the project view only the android source sets are configured correctly. I then get no code intelligence when editing files in any of the other source sets.
![image](https://user-images.githubusercontent.com/401214/140190603-a4c583d0-7b46-43d8-ae9d-b8593f021cf4.png)

As soon as I remove the plugin and sync again, all of the source sets get added back to the IDE:
![image](https://user-images.githubusercontent.com/401214/140190807-6313e437-d5a0-4004-94a0-28a065caba56.png)

Any ideas what could be causing this or how to diagnose it further? The plugin seems quite simple so I'm not sure why this would happen. I tried disabling all other third party plugins in the module (just keeping kotlin and android plugins) and I still have the same issue.

**Comment by rickclephas** [comment]
The gradle plugin will automatically add the `core` and `annotations` dependencies to the `commonMain` sourceset.
Currently these only support JVM, iOS, macOS, watchOS and tvOS targets. 
Which is probably causing the issue since you also have a JS target.

I will have to take a look at adding other targets as well.
Since the whole library is no-op on non Apple targets that shouldn't be a big issue.

In the mean time you could manually add the `kmp-nativecoroutines-core` dependency to your Apple targets and define the native properties and functions yourself instead of using the plugin.

**Comment by drampelt** [comment]
Ah that makes sense. I'll give that a try, thanks!

**Comment by rickclephas** [comment]
[v0.8.0](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v0.8.0) adds support for both the `js` and `linuxX64` target.
This should fix any issues with the plugin not working in projects that use these targets.
