### ISSUE TITLE
Artifacts transitively imported in a compiled .aar

### ISSUE THREAD

**Issue by borsini** [rickclephas/KMP-NativeCoroutines#153]
Hello Rick and thanks for your library👋 

We have a KMP library currently published as an Android .aar and an iOS  .xcframework.

In our Android project using this lib, we use [DependencyGuard](https://github.com/dropbox/dependency-guard) to prevent any unwanted transitive dependency to be included.

We noticed that once we add `KMP-NativeCoroutines` to our KMP library and publish it through Maven, the resulting .aar pulls those 4 transitive dependencies with it 

```
com.rickclephas.kmp:kmp-nativecoroutines-annotations-jvm:1.0.0-ALPHA-18
com.rickclephas.kmp:kmp-nativecoroutines-annotations:1.0.0-ALPHA-18
com.rickclephas.kmp:kmp-nativecoroutines-core-jvm:1.0.0-ALPHA-18
com.rickclephas.kmp:kmp-nativecoroutines-core:1.0.0-ALPHA-18
```

The `pom.xml` and `module.json` confirm it, as we see these dependencies declared 

Do these dependencies need to be included in the aar ? From what I understand, KMP-NativeCoroutines only add some plumbing to the iOS project, not the Android one.

Thanks in advance for your answer!

**Comment by rickclephas** [comment]
Hi @borsini yeah that's correct. Both the `core` and `annotations` dependencies are added to `commonMain` which in turn means they are also added to the android target and the aar.

For non Apple targets these dependencies have the following effect:
* `annotations`: provides the KMP-NativeCoroutines annotations which are needed in `commonMain`
* `core`: provides the `kotlinx.coroutines` dependency (the KMP-NativeCoroutines functions are only included in Apple targets)

Now that I am looking at this, I guess we could make the annotations optional and only implement them for Apple targets.
However that wouldn't remove the dependency since those annotations are stil needed in `commonMain` (meaning the library needs to "support" other targets like JVM to be compatible with all project types).

**Comment by borsini** [comment]
Thanks for the explanation, I found [where](https://github.com/rickclephas/KMP-NativeCoroutines/blob/22d82453f0b836d7b1a729f34bc9cf49515cd522/kmp-nativecoroutines-gradle-plugin/src/main/kotlin/com/rickclephas/kmp/nativecoroutines/gradle/KmpNativeCoroutinesPlugin.kt#L27-L30) those dependencies are added. 
Another option would be to add those dependencies only for `iosMain`. Problem will be that annotations won't be accessible from `commonMain`. Maybe could be worked out using expect/actual.

**Comment by rickclephas** [comment]
> Another option would be to add those dependencies only for iosMain. Problem will be that annotations won't be accessible from commonMain. Maybe could be worked out using expect/actual.

Correct, however we won't be able to remove the JVM target even when using expect/actual.
The "issue" is that we want these dependencies to be added to `commonMain` which requires the dependencies to support all targets in a project. When we would drop the JVM target from `core` and `annotations` any project that includes a JVM target won't be able to use the annotations in `commonMain` anymore.

> A last option would be to ship those dependencies, but as a NoOp empty version on JVM.

That's pretty much what is happening now. While the annotations are still there in JVM they don't have any effect.
The core dependency is completely [empty](https://github.com/rickclephas/KMP-NativeCoroutines/blob/22d82453f0b836d7b1a729f34bc9cf49515cd522/kmp-nativecoroutines-core/src/commonMain/kotlin/com/rickclephas/kmp/nativecoroutines/Empty.kt) for all non-Apple targets.
