### ISSUE TITLE
Not passing suspend functions to Swift even if annotation is present.

### ISSUE THREAD

**Issue by checoalejandro** [rickclephas/KMP-NativeCoroutines#166]
When running v1.0.0-ALPHA-27, ksp at 1.9.23 and kotlin at 1.9.23, when syncing framework, output is not exposing or bringing suspend functions annotated with `@NativeCoroutines` in this last. If I downgrade to v1.0.0-ALPHA-25 and kotlin and ksp to 1.9.22, everything comes back to normal and functions are exposed as expected.

**Comment by rickclephas** [comment]
Hi. Could you possibly share the relevant Kotlin code?

**Comment by checoalejandro** [comment]
Sure, let me know if this is enough:

commonMain:
```
@NativeCoroutines
override suspend fun setDefaultFeaturedWatchlist(uuid: String): DataState<Boolean> {
        return try {
              ... 
```

Swift (function was not found in XCode):
```
self.handle = Task {
            do {
                let changed = try await asyncFunction(for: repository.setDefaultFeaturedWatchlist(uuid: uuid))
                if let succeed = changed.data {
                    print("Default changed: \(succeed)")
                }
            } catch {
                print("Error while changing default selection: \(error.localizedDescription)")
            }
        }
```

**Comment by rickclephas** [comment]
Thanks! In [v1.0.0-ALPHA-27](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-27) support for override and actual declarations have been improved to prevent the plugin from generating duplicate extension functions/properties.

Previously it wasn't recommended to annotate override functions (which resulted in warnings), however the plugin did actually generate extensions when the annotation was present.

Since v1.0.0-ALPHA-27 annotations are allowed on override functions/properties, but they are ignored by the code generator.

Is this function an implementation of some kind of interface? That would explain why the extension function is no longer visible as a regular class function. In that case it would be exposed as a top-level function.
Something like `MyInterfaceNativeKt. setDefaultFeaturedWatchlist(repository, uuid: uuid)`.

**Comment by checoalejandro** [comment]
Okay, I see now, yes, those come from an interface, what should be the proper implementation now? Should I remove the annotation then from the override function?

Thanks

**Comment by checoalejandro** [comment]
Oh I see, do I need to do:
```
UserRepositoryCWWKt.setDefaultFeaturedWatchlist(repository, uuid: uuid)
```
Correct?

**Comment by checoalejandro** [comment]
Thanks, It is now working as expected.

**Comment by rickclephas** [comment]
> Should I remove the annotation then from the override function?

You may keep the annotation on the override function.



> Oh I see, do I need to do:
> 
> ```
> UserRepositoryCWWKt.setDefaultFeaturedWatchlist(repository, uuid: uuid)
> ```
> 
> Correct?

Yeah the exact naming depends on the names of your files, but something like that.
Generally it would be `<FileNameFromInterface>NativeKt.<functionName>`
