### ISSUE TITLE
Annotating fields in subclasses

### ISSUE THREAD

**Issue by DmitriyZaitsev** [rickclephas/KMP-NativeCoroutines#167]
Hi there! I've been using your library with KMMViewModel for a while now, and with the latest update to ALPHA-27, everything broke for me. I noticed in [ release notes](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-27) the quote "annotations are now allowed (but ignored) on override and actual declarations." Given this change, I have an issue with a fairly large amount of existing code.

The issue is that I had a base view model that was inherited by dozens of others. The extensions "uiStateFlow" and "uiStateValue" are no longer generated for subclasses. For now, I'll stick with ALPHA-26, but am I correct in assuming that I won't be able to abstract the "uiState" property in the base class anymore? Thanks!

```
abstract class BaseViewModel<TState : Any> : KMMViewModel() {
    @NativeCoroutinesState
    abstract val uiState: StateFlow<TState>

    /* .. */
}

class FooViewModel() : BaseViewModel<FooState>() {
    private val _uiState = MutableStateFlow(viewModelScope, FooState())

    @NativeCoroutinesState
    override val uiState: StateFlow<FooState> = _uiState.asStateFlow()

    /* .. */
}
```

**Comment by rickclephas** [comment]
Hi! 

> The extensions "uiStateFlow" and "uiStateValue" are no longer generated for subclasses.

Correct. In previous version it was discouraged to use the annotations on overrides as that resulted in the plugin generating duplicate extensions. However those extensions should still be generated for the base declarations in `BaseViewModel`.

> but am I correct in assuming that I won't be able to abstract the "uiState" property in the base class anymore?

We can definitely solve this. Just to confirm: you are still seeing the `uiStateFlow` and `uiStateValue` extensions for the `BaseViewModel`, correct?
I am guessing the issue is that since those are generic extensions the type will be `Any` when used from Swift.

#### Exposing the state value manually

Since you are using KMM-ViewModel you probably only need access to the actual value, right?
In that case (since you already have an abstraction) you could easily create the needed property manually:
```kotlin
@HiddenFromObjC
abstract val uiState: StateFlow<TState>

@ObjCName("uiState")
val uiStateValue: TState get() = uiState.value
```

Removing the need for `@NativeCoroutinesState` and the generic extension properties.

Let me know if that is sufficient for your use case.

**Comment by DmitriyZaitsev** [comment]
I appreciate the advice, @rickclephas!
The solution you provided works perfectly for my use case.
While I'm not eager to add another public property to the interface of the common class, I can accept it as a "necessary evil." 👍
