### ISSUE TITLE
Generic types with @NativeCoroutines

### ISSUE THREAD

**Issue by daniellfalcao** [rickclephas/KMP-NativeCoroutines#180]
I'm trying to create a generic function with the following signature:

```kotlin
actual class OperationResult<T> actual constructor(private val block: suspend () -> T) {

    @NativeCoroutines
    suspend fun getResult(): T = block()
}
```

When I call `asyncFunction` from swift where the return type of the code is an `OperationResult<String>`, for example, the return of `.getResult()` becomes Any. Is there anything that can be done to avoid casting on the Swift side?

Ex:
![Screenshot 2024-06-25 at 18 05 04](https://github.com/rickclephas/KMP-NativeCoroutines/assets/35662363/49a94024-cfd9-4817-826f-e539d8ef420e)

**Comment by daniellfalcao** [comment]
Without using the annotation, Swift can resolve the type correctly.

![Screenshot 2024-06-25 at 18 40 35](https://github.com/rickclephas/KMP-NativeCoroutines/assets/35662363/8e4907aa-fe75-440e-9af6-0cdf3d7ca87f)

**Comment by rickclephas** [comment]
This is an unfortunate limitation of the KSP usage and Kotlin-Swift interop.
In this case, the plugin will generate a generic extension, which is unfortunately not supported.
These generics are lost in translation to Swift.

Since it seems your code is in an Apple/iOS source set, you could manually create the necessary code inside the class:

```kotlin
import com.rickclephas.kmp.nativecoroutines.nativeSuspend
import kotlin.native.ObjCName

@ObjCName(name = "getResult")
fun getResultNative() = nativeSuspend { getResult() }
```

Just annotate your original function with `@HiddenFromObjC` to prevent name conflicts.

**Comment by daniellfalcao** [comment]
It works!!! Thank you!

![Screenshot 2024-06-26 at 08 07 43](https://github.com/rickclephas/KMP-NativeCoroutines/assets/35662363/820e897b-3b3c-45dc-9ce1-c8a001035005)
