### ISSUE TITLE
Is it possible to use shared flows with onChange and onReceive modifiers?

### ISSUE THREAD

**Issue by osrl** [rickclephas/KMP-NativeCoroutines#184]
I have this flows in my kotlin code:

```kotlin
    private val _event1 = MutableStateFlow(false)
    @NativeCoroutinesState
    val event1 = _event1

    private val _event2 = MutableSharedFlow<Boolean>()
    @NativeCoroutines
    val event2 = _event2
```
But I can't use shared flow on my swift code.

![Screenshot 2024-08-07 at 13 12 48](https://github.com/user-attachments/assets/803c58a4-ad60-49a1-9457-4476a02d43ca)

I also tried without `$`. Is it possible to use shared flows with onChange and onReceive modifiers?

**Comment by osrl** [comment]
For a workaround, I used .task and `asyncSequence` function

**Comment by rickclephas** [comment]
`onChange` only requires a value, which is why it's working for your `@NativeCoroutinesState` property.
A `SharedFlow` doesn't have a single value, but it does have a `replayCache`. You could try and use that as the value:
```swift
.onChange(of: eventDispatcher.event2ReplayCache) { event in }
```

`onReceive` requires a Combine Publisher. You can create a publisher for any kind of flow:
```swift
let publisher = createPublisher(for: eventDispatcher.event2)
```
One thing to be aware of is that this will create a new publisher and therefore a new Flow collection every time.
So you would probably need to store this publisher in a viewmodel or something instead of calling the `createPublisher(for:)` function in your SwiftUI body.
