### ISSUE TITLE
@NativeCoroutinesState for val overriden from an interface

### ISSUE THREAD

**Issue by BorisKorec** [rickclephas/KMP-NativeCoroutines#185]
Hi, we're using this library for some time and recently we updated to version [v1.0.0-ALPHA-31](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-31). Unfortunately, `@NativeCoroutinesState` no longer works for properties overriden from an interface. I'm aware that it might be related to the change in this release [v1.0.0-ALPHA-27](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-27).  I've seen some possibly related issues here but none of them helped me to resolve mine so sorry if it seems to be duplicate.

Here's a simplified example:
```
interface TitleProvider {
    @NativeCoroutinesState
    val title: MutableStateFlow<String>
}

open class MyViewModel(): TitleProvider {
    @NativeCoroutinesState  
    override val title: MutableStateFlow<String> = MutableStateFlow("Title")
}
```

It worked well before - we got `title` and `titleFlow` in Swift. This is no longer the case. Any advice would be much appreciated. Thank you!

**Comment by rickclephas** [comment]
> I'm aware that it might be related to the change in this release [v1.0.0-ALPHA-27](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-27).

Correct. The plugin no longer generates duplicate declarations (for override and actual declarations).

The reason you aren't seeing the `title` and `titleFlow` properties is due to a limitation in the Kotlin-ObjC interop.
At the moment the plugin uses KSP to generate extensions. Unfortunately extensions aren't supported on protocols/interfaces in ObjC.

You should be able to access these extension properties as static members on a file class.
E.g. if your `TitleProvider` is inside a `TitleProvider.kt` file, then `TitleProviderNativeKt.title` should be the extension property. It's probably a function accepting the `TitleProvider` instance.

To make usage from Swift easier you can manually create an extension in Swift, e.g. something like:
```swift
extension TitleProvider {
    var title: String { TitleProviderNativeKt.title(self) }
}
```

**Comment by BorisKorec** [comment]
Thank you very much for your quick response. Yes, your suggested solution works well. Even though it's an extra step, but at least we do it only once per interface. Also, we can now remove annotations from components implementing the interface which is nice.
