### ISSUE TITLE
Flow/Combine: Type mismatch using createPublisher() for non-primitives

### ISSUE THREAD

**Issue by jlnstrk** [rickclephas/KMP-NativeCoroutines#77]
Together with Kotlin 1.7.20, I'm using version 0.13.1 of both the Gradle/Kotlin plugin and the Swift package.
I'm trying to use the Combine implementation to wrap a Flow (StateFlow) from Swift.

The Kotlin side looks like this:

```kotlin
open class PlayerViewModel : SharedViewModel() {
    private val _frontendState: MutableStateFlow<FrontendState> = MutableStateFlow(FrontendState.Disconnected)
    val frontendState: StateFlow<FrontendState> get() = _frontendState

    // ...
}
```

And this is the Swift side:

```swift
import Foundation
import Shared
import KMPNativeCoroutinesCombine
import Combine

class PlayerViewModelShim: ObservableObject {
    private let delegate = Shared.PlayerViewModel()

    @Published var frontendState: FrontendState?

    init() {
        createPublisher(for: delegate.frontendStateNative) // error
            .receive(on: DispatchQueue.main)
            .assign(to: \.frontendState, on: self)
    }

    // ...
}
```

where `FrontendState` is some Kotlin sealed class.

This yields the following Swift compile error:

```bash
PlayerViewModelShim.swift:22:39: Cannot convert value of type '(@escaping (FrontendState, KotlinUnit) -> KotlinUnit, @escaping ((any Error)?, KotlinUnit) -> KotlinUnit) -> () -> KotlinUnit' to expected argument type '(@escaping (FrontendState?, KotlinUnit) -> KotlinUnit, @escaping (Never?, KotlinUnit) -> KotlinUnit) -> () -> KotlinUnit
```

Note that consuming the same `Flow` using the Async implementation and `asyncStream` very much compiles.

As it stands, the sample of this project compiles as well.
However, this seems to be related to the fact that a `Flow` of mere `Long`s is being consumed there; swapping for some arbitrary complex type also breaks Swift compilation of the sample.

**Comment by rickclephas** [comment]
The error you are seeing is because `assign(to:on:)` is only available on publishers with a `Failure` type of `Never`.
You can use [`replaceError(with:)`](https://developer.apple.com/documentation/combine/publisher/replaceerror(with:)) or [`assertNoFailure(_:file:line:)`](https://developer.apple.com/documentation/combine/publisher/assertnofailure(_:file:line:)) to get a `Publisher` with a `Failure` type of `Never`.

P.S. `assign(to:on:)` returns an `AnyCancellable` that should be stored to prevent the publisher from being cancelled.
Alternatively you could use [`assign(to:)`](https://developer.apple.com/documentation/combine/publisher/assign(to:)) (which is iOS 14+).

**Comment by jlnstrk** [comment]
@rickclephas Ohhh. Well. Long time no Swift 🙃. Error in an innocent line because of premature reverse-direction type inference. Love it. Anyways, thanks a lot for the heads up & sorry for bothering!
