### ISSUE TITLE
Conversion of observables to @Published values

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [rickclephas/KMP-NativeCoroutines#87]
Hi @rickclephas 
First of all, thanks for this amazing library and your hard work 💯

I'm using the RxSwift implementation of this library in my code and I want to convert an observable to a @ Published value. Following is the warning I'm getting while trying to do so:

<img width="1512" alt="Screenshot 2022-12-28 at 10 54 23 AM" src="https://user-images.githubusercontent.com/46640516/209762039-d1d4246b-7cc6-4178-b587-73ed69d63240.png">

Could you please suggest a fix for this or help out if there's a better way to achieve the same result?

Coming from the Android world, I'm used to converting Flows/LiveData into Compose's state by helper functions like `collectAsState`, `observeAsState`, etc and I want to have a similar experience in SwiftUI as well. How can I achieve that?

**Comment by rickclephas** [comment]
Hi, thanks for the kind words!

The warning you are seeing is because (by default) native coroutines code is executed on a background thread  (`Dispatchers.Default`). Since it's not allowed to update the SwiftUI state from a background thread you can use the `observeOn(_:)` function:
```swift
disposable = createObservable(for: flow)
    .observeOn(MainScheduler.instance)
    .subscribe(onNext: { [weak self] state in
        self?.value = state
    })
```

Alternatively you could use a custom `CoroutineScope` with `Dispatchers.Main` in your Kotlin code.
See https://github.com/rickclephas/KMP-NativeCoroutines/tree/master#custom-coroutinescope.
However in that case your flow (and any other native coroutines code in that class) will run on the main thread.

Btw you can use the `NativeFlow` [typealias](https://github.com/rickclephas/KMP-NativeCoroutines/blob/216daf0daf2b2ae98a60748e0a07841873f1ed54/KMPNativeCoroutinesCore/NativeFlow.swift#L12) for your flow paramater.

P.S. if you are using this in the context of a ViewModel you might want to look at [KMM-ViewModel](https://github.com/rickclephas/KMM-ViewModel) 😇 .

**Comment by shubhamsinghshubham777** [comment]
This works perfectly fine as soon as I run the app 💯 Thanks Rick! I had tried it before but never run the app and just assumed that the warning would go away as soon as I'm using the right code (old Android Studio habits 😂).

Also, I might not be able to use KMM-ViewModel since my app is supporting Android, iOS and JS and I have created a shared ViewModel for all the platforms.

Nevertheless, Closing this issue now. Thanks again for the help 🙌🏻
