### ISSUE TITLE
Functional Interface Functions Do Not Get Generated In 1.0.0-ALPHA-4

### ISSUE THREAD

**Issue by KwabenBerko** [rickclephas/KMP-NativeCoroutines#91]
I have the following functional SAM interface for a usecase class:
```kotlin
fun interface GetCurrencies {
    operator fun invoke(filter: String?): Flow<List<Currency>>
}
```

And in my dependency inversion container, I provide an implementation like so:

```kotlin
val getCurrencies: GetCurrencies by lazy {
    return@lazy GetCurrencies(currencyRepository::getCurrencies)
}
```

I use this pattern to avoid boilerplate for usecase classes that only forward calls to the repository(https://betterprogramming.pub/how-to-avoid-use-cases-boilerplate-in-android-d0c9aa27ef27)
This pattern used to work for the `0.13.3` version when the library converted all flows. This does not work though in the `1.0.0-ALPHA-4` version, even if I annotate the interface and repository functions with @NativeCoroutines annotation.

**Comment by rickclephas** [comment]
Hi sorry for the delay! Just tested this and it's working, but there is a catch. Assuming your code is:
```kotlin
// file: GetCurrencies.kt
fun interface GetCurrencies {
    @NativeCoroutines
    operator fun invoke(filter: String?): Flow<List<Currency>>
}
```

KMP-NativeCoroutines will correctly generate an extension function for `invoke`.
However since `GetCurrencies` is an interface it isn't accessible directly due to some Kotlin ObjC interop limitations.
To access `invoke` from Swift you would need to use the following code:
```swift
let getCurrencies: GetCurrencies
let publisher = asyncPublisher(for: GetCurrenciesNativeKt.invoke(getCurrencies, filter: nil))
```
Note: I used `asyncPublisher(for:)`, but you can use other Swift implementations as well.

To make this a little easier to use you could add your own Swift extension to `GetCurrencies`.
